# Custom API Key (???? ??)
tmdb.api.key=f7043ebec102d62857ae44f022858445

# Application Configuration
spring.application.name=myflix
server.port=8080

# Thymeleaf Template Configuration (?? ? false ??)
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Server Encoding Configuration (?? Spring Boot ??)
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true